version: 2

sources:
  - name: northwind_etl
    description: This is a replica of the Postgres database used by our client.
    tables:
      - name: orders
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
      - name: order_details
      - name: products
      - name: customers
      - name: employees
      - name: shippers
      - name: suppliers
            